### PR TITLE
Add feasst

### PR DESCRIPTION
**Pull request by HaroldHatchNIST**
## FEASST

The repository complies with our [Terms of Use][_ntos].

- [x] README.md or README.rst clearly describes, in layman's terms:
  - [x] goals of the repository and project
  - [x] whether the code is usable (pre-release, production-ready, or in-between?)
  - [x] how to get in touch with the development team
  - [x] acknowledges collaborators and reused code, if applicable
- [x] Documentation exists, in README.md or separately, and explains
  - [x] dependencies, if any
  - [x] installation process
  - [x] basic usage
- [x] LICENSE.md or LICENSE.txt dedicates the software to the public domain using
      [approved language][_dirl], preferably a duplicate of [LICENSE.md][_stdl]

## Maturity Checklist *(bonus)*

The repository demonstrates mature development practices, including
integration with services that improve maintainability and an overall
commitment to helping newcomers quickly achieve proficiency.

- [ ] Developers leverage GitHub as a communication tool
  - [ ] Description, Website, and Topics fields are meaningfully populated
  - [ ] Closed pull requests indicate a [branching][_brwf] or otherwise
        consistent workflow
  - [ ] Merged pull requests underwent formal [code review][_ghrv]
  - [ ] Badges in README.md display positive status messages
  - [x] CONTRIBUTING.md provides clear guidance on
    - [x] where the stable code resides, if not on `master`
    - [x] expected workflow and release process (rolling, [semver][_smvr], or other)
- [x] Self-documenting code with link to online docs
  - [x] using [Doxygen][_doxy], [Docstrings][_docs], or similar
  - [x] hosted by [NIST][_nstp], [readthedocs][_rtfd], or similar
  - [x] provides worked examples and tutorials
- [1/2] Tests automatically run on... my local machine (not travis, etc)
- [ ] Insights tab on GitHub indicates a healthy software environment
  - [ ] Contributors shows a history of commits (not just one)
  - [ ] Dependency Graph does not flag security vulnerabilities
- [ ] Git branches are used appropriately

## Further Justification

This software has been presented at a conference and is slowly adding
external users.

[_brwf]: https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows
[_crcl]: https://circleci.com
[_dirl]: https://www.nist.gov/director/licensing
[_docs]: https://www.python.org/dev/peps/pep-0257/
[_doxy]: https://www.stack.nl/~dimitri/doxygen
[_ghrv]: https://help.github.com/articles/about-pull-request-reviews/
[_nstp]: https://pages.nist.gov
[_ntos]: http://odiwiki.nist.gov/ODI/GitHubFAQ#Public_Repository_Guidelines
[_rtfd]: https://readthedocs.org
[_smvr]: https://semver.org
[_stdl]: https://github.com/usnistgov/awesome-nist/blob/master/LICENSE.md
[_trvs]: https://travis-ci.org

### CODE REVIEW

**Comment by tkphd** [comment]
## Baseline Checklist *(prerequisite)*

The repository complies with our [Terms of Use][_ntos].

- [x] README.md or README.rst clearly describes, in layman's terms:
  - [x] goals of the repository and project
  - [x] whether the code is usable (pre-release, per semantic versioning)
  - [x] how to get in touch with the development team
  - [x] acknowledges collaborators and reused code, if applicable
- [x] Documentation exists, in README.md or separately, and explains
  - [x] dependencies, if any
  - [x] installation process
  - [x] basic usage
- [x] LICENSE.md or LICENSE.txt dedicates the software to the public domain using
      [approved language][_dirl], preferably a duplicate of [LICENSE.md][_stdl]

## Maturity Checklist *(bonus)*

The repository demonstrates mature development practices, including
integration with services that improve maintainability and an overall
commitment to helping newcomers quickly achieve proficiency.

- [x] Developers leverage GitHub as a communication tool
  - [x] Description, Website, and Topics fields are meaningfully populated
  - [ ] Closed pull requests indicate a [branching][_brwf] or otherwise
        consistent workflow
  - [ ] Merged pull requests underwent formal [code review][_ghrv]
  - [ ] Badges in README.md display positive status messages
  - [x] CONTRIBUTING.md provides clear guidance on
    - [ ] where the stable code resides, if not on `master`
    - [x] expected workflow and release process (rolling, [semver][_smvr], or other)
- [x] Self-documenting code with link to online docs
  - [x] using [Doxygen][_doxy]
  - [x] hosted by [NIST][_nstp]
  - [x] provides worked examples and tutorials
- [ ] Tests automatically run on a continuous integration service,
      *e.g.* [Travis CI][_trvs], [Circle][_crcl], or similar
- [x] Insights tab on GitHub indicates a healthy software environment
  - [x] Contributors shows a history of commits (not just one)
  - [x] Dependency Graph does not flag security vulnerabilities
- [x] Git branches are used appropriately

## Further Justification

In addition to the generic items selected above, this repository is *awesome*
because it clearly and effectively communicates about the theory (via papers)
and implementation (via documentation) using GitHub and NIST Pages. 
README provides a deep, yet high-level overview of what it's about, and the
self-documenting code provides a lot of useful insight. Also, the folder "unittests"
implies continuous integration is coming soon.


[_brwf]: https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows
[_crcl]: https://circleci.com
[_dirl]: https://www.nist.gov/director/licensing
[_docs]: https://www.python.org/dev/peps/pep-0257/
[_doxy]: https://www.stack.nl/~dimitri/doxygen
[_ghrv]: https://help.github.com/articles/about-pull-request-reviews/
[_nstp]: https://pages.nist.gov
[_ntos]: http://odiwiki.nist.gov/ODI/GitHubFAQ#Public_Repository_Guidelines
[_rtfd]: https://readthedocs.org
[_smvr]: https://semver.org
[_stdl]: https://github.com/usnistgov/awesome-nist/blob/master/LICENSE.md
[_trvs]: https://travis-ci.org

**Review by tkphd — CHANGES_REQUESTED** [review]
Alphabetical order is preferred.

**Comment by ianhbell** [comment]
PM sent regarding externals

**Comment by ianhbell** [comment]
Also, the example in the README seems to be missing (I guess this would get included in the docs build), but a copy-paste might be the right solution here.

As an aside, are you using the new FindPython module for Python?  From my experience, it is really very robust and you might be able to get away with removing the notes about the PYTHON_EXECUTABLE and PYTHON_INCLUDES, which tends to make the builds un-generalized.

**Comment by HaroldHatchNIST** [comment]
Thank you all for putting the work into looking over this code. I really appreciate it.

Updated [alphabetical order](https://github.com/usnistgov/awesome-nist/pull/29/commits/e61406f02363fdbb7750cc7b94f93685ec005949#diff-04c6e90faac2675aa89e2176d2eec7d8R26).

Unittests are included in src and tutorial.

Ian Bell brought up some things which I will address in my next commit in FEASST after long tests pass. For the example in the README, I will make an exception to "no copy-paste." For FindPython (requires cmake 3.0+?), I think I had held off on that because some users are still using cmake 2.8.12, but I could be wrong.

**Review by tkphd — APPROVED** [review]

**Pull request merged**
