### PR TITLE
Add ChebTools?

### PR DESCRIPTION
**Pull request by ianhbell**
### Baseline Checklist *(prerequisite)*
The repository complies with our [Terms of Use][_ntos].

- [X] README.md or README.rst clearly describes, in layman's terms:
  - [X] goals of the repository and project
  - [X] whether the code is usable (pre-release, production-ready, or in-between?)
  - [X] how to get in touch with the development team
  - [X] acknowledges collaborators and reused code, if applicable
- [X] Documentation exists, in README.md or separately, and explains
  - [X] dependencies, if any
  - [X] installation process
  - [X] basic usage
- [X] LICENSE.md or LICENSE.txt dedicates the software to the public domain using
      [approved language][_dirl], preferably a duplicate of [LICENSE.md][_stdl]

### Maturity Checklist *(bonus)*
The repository demonstrates mature development practices, including
integration with services that improve maintainability and an overall
commitment to helping newcomers quickly achieve proficiency.

- [X] Developers leverage GitHub as a communication tool
  - [X] Description, Website, and Topics fields are meaningfully populated
  - [X] Closed pull requests indicate a [branching][_brwf] or otherwise
        consistent workflow
  - [X] Merged pull requests underwent formal [code review][_ghrv]
  - [X] Badges in README.md display positive status messages
  - [X] CONTRIBUTING.md provides clear guidance on
    - [] where the stable code resides, if not on `master`
    - [] expected workflow and release process (rolling, [semver][_smvr], or other)
- [ ] Self-documenting code with link to online docs
  - [ ] using [Doxygen][_doxy], [Docstrings][_docs], or similar
  - [ ] hosted on https://pages.nist.gov, [readthedocs][_rtfd], or similar
  - [ ] provides worked examples and tutorials
- [X] Tests automatically run on a continuous integration service,
      *e.g.* [Travis CI][_trvs], [Circle][_crcl], or similar
- [x] Insights tab on GitHub indicates a healthy software environment
  - [x] Contributors shows a history of commits (not just one)
  - [x] Dependency Graph does not flag security vulnerabilities
- [ ] Git branches are used appropriately

### Further Justification
In addition to the generic items selected above, this repository is *awesome*
because...

* edited to fix link in top-level heading *

[_brwf]:  https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows
[_crcl]:  https://circleci.com
[_dirl]:  https://www.nist.gov/director/licensing
[_docs]:  https://www.python.org/dev/peps/pep-0257/
[_doxy]:  https://www.stack.nl/~dimitri/doxygen
[_ghrv]:  https://help.github.com/articles/about-pull-request-reviews/
[_ntos]:  http://odiwiki.nist.gov/ODI/GitHubFAQ#Public_Repository_Guidelines
[_rtfd]:  https://readthedocs.org
[_smvr]:  https://semver.org
[_stdl]:  https://github.com/usnistgov/awesome-nist/blob/master/LICENSE.md
[_trvs]:  https://travis-ci.org

### CODE REVIEW

**Comment by tkphd** [comment]
Nominations, especially of your own work, should be filed as [issues](https://github.com/usnistgov/USNISTGOV/issues), not pull requests. I'll update CONTRIBUTING.md to reflect this, thanks!

**Comment by tkphd** [comment]
Per the revised [workflow](/usnistgov/awesome-nist/blob/master/CONTRIBUTING.md),  submitting a pull request is considered preferable -- thanks for the contribution.

## Baseline Checklist *(prerequisite)*

The repository complies with our [Terms of Use][_ntos].

- [ ] README.md or README.rst clearly describes, in layman's terms:
  - [x] goals of the repository and project (duplicate MatLab's chebfun library)
  - [x] whether the code is usable (v1.0)
  - [ ] how to get in touch with the development team
  - [ ] acknowledges collaborators and reused code, if applicable
    - Silently leans on Eigen for efficient matrix manipulation
- [ ] Documentation exists, in README.md and a JOSS article, and explaining
  - [x] dependencies, if any
  - [x] installation process
  - [x] basic usage
- [ ] LICENSE.md or LICENSE.txt dedicates the software to the public domain using
      [approved language][_dirl], preferably a duplicate of [LICENSE.md][_stdl]
    - LICENSE assigns copyright to the Secretary of Commerce, which is unlawful per 17USC105.
    - LICENSE contains the MIT License, rather than a dedication to the public domain.

## Maturity Checklist *(bonus)*

The repository demonstrates mature development practices, including
integration with services that improve maintainability and an overall
commitment to helping newcomers quickly achieve proficiency.

- [ ] Developers leverage GitHub as a communication tool
  - [ ] Description, Website, and Topics fields are meaningfully populated
  - [ ] Closed pull requests indicate a [branching][_brwf] or otherwise
        consistent workflow
  - [ ] Merged pull requests underwent formal [code review][_ghrv]
  - [x] Badges in README.md display positive status messages
  - [ ] CONTRIBUTING.md provides clear guidance on
    - [ ] where the stable code resides, if not on `master`
    - [ ] expected workflow and release process (rolling, [semver][_smvr], or other)
- [ ] Self-documenting code with link to online docs
  - [Doxygen][_doxy] is used, but documentation build is undocumented and apparently only for local build.
  - [Docstrings][_docs] are not used.
  - [x] provides worked example/tutorial in a Jupyter notebook
- [x] Tests automatically run on a continuous integration service,
      *e.g.* [Travis CI][_trvs], [Circle][_crcl], or similar
- [x] Insights tab on GitHub indicates a healthy software environment
  - [x] Contributors shows a history of commits (not just one)
  - [x] Dependency Graph does not flag security vulnerabilities
- [ ] Git branches are used appropriately

## Further Justification

ChebTools is a fairly simple library, essentially providing a Python wrapper around a single C++ file.
This small footprint is possible due to effective leveraging of external open-source projects. It features Travis-CI integration, a decent README backed up by a JOSS article, and provides a Jupyter notebook for demonstration.

At present, however, the deficiencies summarized above -- as well as the fact that its core dependency, Eigen, has dropped offline -- prevents ChebTools from being considered awesome at this time.



[_brwf]: https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows
[_crcl]: https://circleci.com
[_dirl]: https://www.nist.gov/director/licensing
[_docs]: https://www.python.org/dev/peps/pep-0257/
[_doxy]: https://www.stack.nl/~dimitri/doxygen
[_ghrv]: https://help.github.com/articles/about-pull-request-reviews/
[_nstp]: https://pages.nist.gov
[_ntos]: http://odiwiki.nist.gov/ODI/GitHubFAQ#Public_Repository_Guidelines
[_rtfd]: https://readthedocs.org
[_smvr]: https://semver.org
[_stdl]: https://github.com/usnistgov/awesome-nist/blob/master/LICENSE.md
[_trvs]: https://travis-ci.org

**Comment by ianhbell** [comment]
Regarding the  above comments:
1) LICENSE: this was a drawn-out discussion with NIST legal, and they accept this compromise according to the new NIST copyright legislation.  JOSS requires an OSI-certified license, of which public domain is not.  This was a LICENSE that all parties (JOSS, NIST legal) were ok with, though neither side was happy.
2) The Eigen dependency is mentioned in the JOSS paper, and is present as a git submodule.  Also now added to README (good idea, and a good practice)

Thanks for the feedback

**Comment by tkphd** [comment]
It's unfortunate that OSI does not recognize the Public Domain as Open Source,
and more unfortunate that JOSS is inflexible on this point. I'm not a lawyer, and
would be fascinated to see the drawn-out discussion that led to this statement:
I believe assignment of copyright to the Secretary of the US Department of Commerce
is unenforceable, and its inclusion here is misleading.

We'll consider this special case.

**Comment by tkphd** [comment]
Your LICENSE does not reconcile with README, which restricts the license to users outside the U.S. That language would have to be inside the LICENSE to make it a valid document.

Also, references to Eigen did not make it into the README, but the new `.gitmodule` seems to fix it.
For the record, including other work in `.gitmodule` (or another machine-readable config file) does not count as documenting your dependencies.

**Comment by agmorey** [comment]
Ian, to make it easier to understand, consider adding an introduction statement in the LICENSE file such as "this code was development by the U.S. Government with the exception of the JOSS directory and  the Eigen module..." and include separate license files such as MIT in subdirectories as needed.  

There is also an MIT graphic inserted by GitHub when you open the license file at [GitHub](https://github.com/usnistgov/ChebTools/blob/master/LICENSE), because you chose a template?

**Comment by ianhbell** [comment]
@tkphd - The License stuff (all of it), is now immutable, and I can't change any of it.  Seriously, it was a major pain to get the licensing things approved by everybody.  I know I'm on the cutting edge - I think I'm only the second library at NIST that has been allowed to have an MIT license according to NIST legal.  This is all still in flux, and you can PM me for more information.

Point taken on the licensing issues for Eigen.  I'll try to do a better job with that in the future, and I just pushed my (forgotten) updates to README

**Comment by guyer** [comment]
@ianhbell Interesting. Has JOSS read [what OSI has to say about U.S. government works](https://opensource.org/faq#public-domain)? Specifically:

> There are certain circumstances, such as with U.S. government works as described above, where it is not easy to apply a license, and the software must be released into the public domain. In these cases, while it would be inaccurate to display the OSI logo or say that the license is OSI-approved (since there is no license), nevertheless we think it is accurate to say that such software is effectively open source, or open source for most practical purposes, even though it is not officially released under an open source license. (This is assuming, of course, that in the laws of releasing jurisdiction the meaning of "public domain" is compatible with the Open Source Definition.) After all, the freedoms guaranteed by open source licenses are still present, and it is possible for the familiar dynamics of open source collaboration to arise around the software.

**Comment by tkphd** [comment]
Thanks for the update, @ianhbell, and thanks for digging up OSI's position on the public domain, @guyer.
I'm satisfied that the license is appropriate, and am adding ChebTools to the list of awesome NIST repos.
Keep up the good work, Ian!

**Pull request merged**
