### PR TITLE
pyPRISM looks awesome

### LINKED ISSUE #1: consider pyprism
https://github.com/usnistgov/pyPRISM

### PR DESCRIPTION
**Pull request by tkphd**
## https://github.com/usnistgov/pyprism
Closes #1.

### Baseline Checklist *(prerequisite)*
- [x] The repository complies with our [Terms of Use][_ntos].

- [ ] README.md clearly describes, in layman's terms:
  - [x] goals of the repository and project
  - [x] whether the code is usable (pre-release, production-ready, or in-between?)
    - checked, based on Release v1.0.0
  - [x] how to get in touch with the development team
  - [ ] acknowledges collaborators and reused code, if applicable
    - not applicable
- [ ] Documentation exists, in README.md or separately, and explains
  - [ ] dependencies, if any
  - [x] installation process
    - using Anaconda virtual environments and conda-forge, or PyPI (pip) package manager
  - [x] basic usage
- [ ] LICENSE.md or LICENSE.txt dedicates the software to the public domain using
      [approved language][_dirl], preferably a duplicate of [LICENSE.md][_stdl]
    - Yes, except that as of writing, LICENSE inserts a personal copyright notice *into* the approved dedication to the public domain.

### Maturity Checklist *(bonus)*
- [x] The repository demonstrates mature development practices, including
   integration with services that improve maintainability and an overall
   commitment to helping newcomers quickly achieve proficiency.

- [x] Developers leverage GitHub as a communication tool
  - [x] Description, Website, and Topics fields are meaningfully populated
  - [ ] Closed pull requests indicate a [branching][_brwf] or otherwise
        consistent workflow
    - Single-contributor workflow: no closed PRs to date.
  - [ ] Merged pull requests underwent formal [code review][_ghrv]
    - Single-contributor workflow: no merged PRs to date.
  - [x] Badges in README.md display positive status messages
  - [x] CONTRIBUTING.md provides clear guidance on
    - [x] where the stable code resides, if not on `master`
    - [ ] expected workflow and release process (rolling, [semver][_smvr], or other)
- [x] Self-documenting code with link to online docs
  - [x] using [Doxygen][_doxy]
  - [x] hosted on [readthedocs][_rtfd]
  - [x] provides worked examples and tutorials
- [ ] Tests automatically run on [Travis CI][_trvs]
    - Integration partially configured: no builds have run to date.
- [ ] Insights tab on GitHub indicates a healthy software environment
  - [x] Contributors shows a history of commits (not just one)
  - [x] Dependency Graph does not flag security vulnerabilities
- [x] Git branches are used appropriately

### Further Justification
In addition to the generic items selected above, this repository is *awesome*
because...
- README.md and readthedocs landing pages are well illustrated, conveying both the basic premise and more advanced theoretical background
- Text is not simple boilerplate: the dev has made a strong effort to explain the project, document the code, and provide resources for newcomers
- Appropriate integration with external services (Travis and RTD) will serve the dev well when collaborators come aboard, or during code rewrites and expansion.

[_brwf]:  https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows
[_crcl]:  https://circleci.com
[_dirl]:  https://www.nist.gov/director/licensing
[_docs]:  https://www.python.org/dev/peps/pep-0257/
[_doxy]:  https://www.stack.nl/~dimitri/doxygen
[_ghrv]:  https://help.github.com/articles/about-pull-request-reviews/
[_ntos]:  http://odiwiki.nist.gov/ODI/GitHubFAQ#Public_Repository_Guidelines
[_rtfd]:  https://readthedocs.org
[_smvr]:  https://semver.org
[_stdl]:  https://github.com/usnistgov/awesome-nist/blob/master/LICENSE.md
[_trvs]:  https://travis-ci.org

---
This change is [Reviewable](https://reviewable.io/reviews/usnistgov/awesome-nist/16)

### CODE REVIEW

**Review by guyer — COMMENTED** [review]
@tkphd `LICENSE` was revised 18 days ago, but even prior to that, I see no sign that "LICENSE inserts a personal copyright notice into the approved dedication to the public domain."

**Review by guyer — APPROVED** [review]

**Comment by tkphd** [comment]
@guyer it was last seen [here](https://github.com/usnistgov/pyPRISM/commit/2e121367ebc8cc6ce994a41c75554957f8df8044#diff-9879d6db96fd29134fc802214163b95a).

**Comment by guyer** [comment]
@tkphd Interesting. Blame doesn't give any indication of deleted lines.

**Comment by tkphd** [comment]
@agmorey and @mnewrock, if you have a chance to review, please do so soon. I would like to get the list started.

**Pull request merged**
